spring:
    application:
        name: exam-eureka

server:
    port: 8763 #启动端口

eureka:
  instance:
    # 主机地址
    hostname: 127.0.0.1
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间剔除
    lease-expiration-duration-in-seconds: 10
    # 使用IP注册
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://{eureka.instance.hostname}:8761/eureka/, http://{eureka.instance.hostname}:8762/eureka/
    # 是否从eureka服务器获取注册信息
    fetch-registry: true
    # 注册自身到eureka服务器
    register-with-eureka: true
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 5
  server:
    #自我保护模式
    enable-self-preservation: true
    # 清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 60000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 6000

logging:
  level: debug
  level.com.sunlands.study: debug
  path: logs/
  file: exam-eureka_c-dev.log