server:
  port: 8088
  servlet:
    context-path: /kekeguo
spring:
  application:
    name: admin
  redis:
    host: 127.0.0.1
    password:
  thymeleaf:
    prefix: classpath:/static/template/
  datasource:
    url: jdbc:mysql://172.16.164.45:3369/study-plan?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/kekeguo/admin/dao/mapper/*.xml
  type-aliases-package: com.kekeguo.admin.model