spring:
    application:
        name: examplan-eureka-a

server:
    #启动端口
    port: 8761

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间剔除
    lease-expiration-duration-in-seconds: 15
    # 使用IP注册
    prefer-ip-address: true
    tatus-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      default-zone: http://{eureka.instance.hostname}:8761/eureka/
    # 是否从eureka服务器获取注册信息  , http://{eureka.instance.hostname}:8763/eureka/
    fetch-registry: false
    # 注册自身到eureka服务器
    register-with-eureka: false
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 1


  server:
    #自我保护模式
    enable-self-preservation: false
    # 清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 6000
    #缓存刷新时间
    response-cache-update-interval-ms: 3000
logging:
  level: error
  level.com.sunlands.study: error
  path: logs/
  file: examplan-eureka_a-dev.log