server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7000
#  servlet:
#    context-path: /examplan-api
##########################################################################################################################
spring:
  application:
    name: examplan-service #指定服务名
##########################################################################################################################
# mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.164.45:3369/transfer-bank?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123
    filters: stat, wall, log4j
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
##########################################################################################################################################################################################
#jackson 属性配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 172.16.164.44
    port: 6379
########################################################################################################################################################
eureka:
    instance:
      instance-id: ${spring.application.name}:${server.port}
      # 心跳间隔
      lease-renewal-interval-in-seconds: 3
      # 服务续约到期时间
      lease-expiration-duration-in-seconds: 15
      statusPageUrlPath: /actuator/info
      healthCheckUrlPath: /actuator/health
      home-page-url-path: /
      prefer-ip-address: true
      ip-address: 127.0.0.1
        # docker 部署开启
    client:
        fetch-registry: true
        # 注册自身到eureka服务器
        register-with-eureka: true
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/  ,http://localhost:8762/eureka/,http://localhost:8763/eureka/
                    # docker 部署开启
            defaultZone: http://localhost:8761/eureka/

########################################################################################################################################################

#pojo别名扫描包
mybatis:
  type-aliases-package: com.sunlands.examplan.entity
  mapper-locations: classpath:/mappings/*Mapper.xml
##########################################################################################################################################################################################
logging:
  path: logs/
  file: examplan-service-dev.log
  level:
    com.sunlands.examplan: DEBUG
##########################################################################################################################
#缓存开关配置
sunlands:
    redis:
      open: true  # 是否开启redis缓存
##########################################################################################################################
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
##########################################################################################################################

